export const products = [
  {
    id: 1,
    title: "Maggi Masala Noodles",
    description: "280 gm",
    price: "45",
    img: "https://www.quicklly.com/upload_images/product/1603647797-maggi-noodles.jpg",
    quantity: 1,
  },
  {
    id: 2,
    title: "Wheel Active",
    description: "1 kg",
    price: "58",
    img: "https://upmarketretail.in/wp-content/uploads/2020/09/Active-Wheel-Detergent-Powder-1-kg.jpg",
    quantity: 1,
  },
  {
    id: 3,
    title: "Gowardhan Cow Ghee",
    description: "1 Ltr",
    price: "580",
    img: "https://images.jdmagicbox.com/grocery/gowardhan-cow-ghee-jar-500-ml-54710-6c0zo.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "Gemini Refined Sunflower Oil Pouch",
    description: "1 Ltr",
    price: "170",
    img: "https://m.media-amazon.com/images/I/71-Y+qbbvsL._SL1251_.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "California Almond - California Badam - Californian Almonds",
    description: "1 Kg",
    price: "850",
    img: "https://m.media-amazon.com/images/I/814-A9IEokL._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 6,
    title: "Vim Lemon Bar",
    description: "200 g (Pack of 6)",
    price: "95",
    img: "https://m.media-amazon.com/images/I/61EkNlHTe2L._SL1000_.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "Green Cardamom",
    description: "100 g",
    price: "200",
    img: "https://m.media-amazon.com/images/I/4190DEhEd-L.jpg",
    quantity: 1,
  },
  {
    id: 8,
    title: "affola Honey, 100% Pure NMR tested Honey",
    description: "1 kg",
    price: "300",
    img: "https://m.media-amazon.com/images/I/61YXINGOkhS._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 9,
    title: "All Out Refill Ultra",
    description: "45 ml",
    price: "70",
    img: "https://m.media-amazon.com/images/I/41fHVe0ZsxL.jpg",
    quantity: 1,
  },
];
